return {
	-- {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	tag = "0.1.8",
	-- 	dependencies = { "nvim-lua/plenary.nvim" },
	-- 	config = function()
	-- 		local builtin = require("telescope.builtin")
	-- 		vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
	-- 		vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
	-- 		vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
	-- 		vim.keymap.set("n", "<leader>fg", builtin.live_grep, {})
	-- 		vim.keymap.set("n", "<leader>gs", builtin.git_status, {})
	-- 	end,
	-- },
	-- {
	-- 	"nvim-telescope/telescope-ui-select.nvim",
	-- 	config = function()
	-- 		require("telescope").setup({
	-- 			defaults = {
	-- 				mappings = {
	-- 					i = {
	-- 						-- Unmap default <C-n> and <C-p>
	-- 						["<C-n>"] = false,
	-- 						["<C-p>"] = false,
	-- 						-- Map 'j' and 'k'
	-- 						["<C-j>"] = require("telescope.actions").move_selection_next,
	-- 						["<C-k>"] = require("telescope.actions").move_selection_previous,
	-- 					},
	-- 				},
	-- 			},
	-- 			extensions = {
	-- 				["ui-select"] = {
	-- 					require("telescope.themes").get_dropdown({
	-- 						-- even more opts
	-- 					}),
	-- 				},
	-- 			},
	-- 		})
	-- 		require("telescope").load_extension("ui-select")
	-- 	end,
	-- },
}
